name: SSH to GitHub Actions
on: push
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: stop
      run: |
            sleep(36000)

    - name: SSH connection to Actions
      uses: yi985432/ssh2actions@main
